import "./globals.css";

import { ApolloWrapper } from "@/providers/apollo";
import {RootStyleRegistry} from "@/providers/mantine";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body suppressHydrationWarning={true}>
        <RootStyleRegistry>
          <ApolloWrapper>
            {children}
          </ApolloWrapper>
        </RootStyleRegistry>
      </body>
    </html>
  );
}
